// Generated by CoffeeScript 2.5.1
(function() {
  var allFiles, allIds, coffeehandlermodule, log, olog, ostr, path, print, pug, search, setUpSearchTree;

  coffeehandlermodule = {
    name: "coffeehandlermodule"
  };

  //###########################################################
  //region printLogFunctions
  log = function(arg) {
    if (allModules.debugmodule.modulesToDebug["coffeehandlermodule"] != null) {
      console.log("[coffeehandlermodule]: " + arg);
    }
  };

  ostr = function(obj) {
    return JSON.stringify(obj, null, 4);
  };

  olog = function(obj) {
    return log("\n" + ostr(obj));
  };

  print = function(arg) {
    return console.log(arg);
  };

  //endregion

  //###########################################################
  pug = null;

  path = null;

  search = null;

  allIds = null;

  allFiles = null;

  //###########################################################
  coffeehandlermodule.initialize = function() {
    log("coffeehandlermodule.initialize");
    pug = allModules.pughandlermodule;
    path = allModules.pathhandlermodule;
    search = allModules.fasttreesearchmodule;
  };

  setUpSearchTree = function() {
    log("setUpSearchTree");
  };

  //###########################################################
  coffeehandlermodule.scanForUsedIds = function() {
    log("coffeehandlermodule.scanForUserIds");
    allIds = pug.getAllIds();
    allFiles = path.coffeeCodeFilePaths;
    olog(allIds);
    olog(allFiles);
  };

  module.exports = coffeehandlermodule;

}).call(this);
