// Generated by CoffeeScript 2.5.1
(function() {
  var allFiles, allIds, coffeehandlermodule, fs, log, olog, ostr, path, print, pug, usedIds;

  coffeehandlermodule = {
    name: "coffeehandlermodule"
  };

  //###########################################################
  //region printLogFunctions
  log = function(arg) {
    if (allModules.debugmodule.modulesToDebug["coffeehandlermodule"] != null) {
      console.log("[coffeehandlermodule]: " + arg);
    }
  };

  ostr = function(obj) {
    return JSON.stringify(obj, null, 4);
  };

  olog = function(obj) {
    return log("\n" + ostr(obj));
  };

  print = function(arg) {
    return console.log(arg);
  };

  //endregion

  //###########################################################
  fs = require("fs");

  //###########################################################
  pug = null;

  path = null;

  allIds = null;

  allFiles = null;

  usedIds = [];

  //###########################################################
  coffeehandlermodule.initialize = function() {
    log("coffeehandlermodule.initialize");
    pug = allModules.pughandlermodule;
    path = allModules.pathhandlermodule;
  };

  //###########################################################
  coffeehandlermodule.scanForUsedIds = function() {
    var coffeeString, file, i, id, j, len, len1;
    log("coffeehandlermodule.scanForUserIds");
    allIds = pug.getAllIds();
    allFiles = path.coffeeCodeFilePaths;
    olog(allIds);
    for (i = 0, len = allIds.length; i < len; i++) {
      id = allIds[i];
      for (j = 0, len1 = allFiles.length; j < len1; j++) {
        file = allFiles[j];
        coffeeString = String(fs.readFileSync(file));
        if (coffeeString.indexOf(id) !== -1) {
          usedIds.push(id);
          break;
        }
      }
    }
    olog(usedIds);
  };

  module.exports = coffeehandlermodule;

}).call(this);
