// Generated by CoffeeScript 2.5.1
(function() {
  var cfg, coffee, log, mainprocessmodule, olog, ostr, path, print, pug;

  mainprocessmodule = {
    name: "mainprocessmodule"
  };

  //###########################################################
  //region logPrintFunctions
  log = function(arg) {
    if (allModules.debugmodule.modulesToDebug["mainprocessmodule"] != null) {
      console.log("[mainprocessmodule]: " + arg);
    }
  };

  olog = function(o) {
    return log("\n" + ostr(o));
  };

  ostr = function(o) {
    return JSON.stringify(o, null, 4);
  };

  print = function(arg) {
    return console.log(arg);
  };

  //endregion

  //###########################################################
  //region localModules
  cfg = null;

  pug = null;

  path = null;

  coffee = null;

  //endregion

  //###########################################################
  mainprocessmodule.initialize = function() {
    log("mainprocessmodule.initialize");
    cfg = allModules.configmodule;
    pug = allModules.pughandlermodule;
    path = allModules.pathhandlermodule;
    coffee = allModules.coffeehandlermodule;
  };

  
  //###########################################################
  mainprocessmodule.execute = async function(e) {
    log("mainprocessmodule.execute");
    await path.preparePugHeadPath(e.pugHead);
    await path.prepareCoffeeCodePath(e.coffeeCode);
    // await path.prepareOutputPath(e.output)
    await pug.readFiles();
  };

  // await coffee.scanForUsedIds()
  // await coffee.writeOutputFile()
  module.exports = mainprocessmodule;

}).call(this);
