// Generated by CoffeeScript 2.5.1
(function() {
  var log, naivsearchmodule, olog, ostr, print;

  naivsearchmodule = {
    name: "naivsearchmodule"
  };

  //###########################################################
  //region printLogFunctions
  log = function(arg) {
    if (allModules.debugmodule.modulesToDebug["naivsearchmodule"] != null) {
      console.log("[naivsearchmodule]: " + arg);
    }
  };

  ostr = function(obj) {
    return JSON.stringify(obj, null, 4);
  };

  olog = function(obj) {
    return log("\n" + ostr(obj));
  };

  print = function(arg) {
    return console.log(arg);
  };

  //endregion

  //###########################################################
  naivsearchmodule.initialize = function() {
    log("naivsearchmodule.initialize");
  };

  module.exports = naivsearchmodule;

}).call(this);
